import Head from 'next/head'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar.js'
import Hero from './components/Hero.js'
import AboutCard from './components/AboutCard.js'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700;800&family=Poppins:wght@400;700&display=swap" rel="stylesheet"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='violetline'></div>
       
      <Navbar/>
     <Hero/>
     <img className='hero__wave' src='hero-wave.png'/>
     <div className='partners'>
     <span className='body__header'>Наши партнеры</span>
    <div style={{display:'flex',justifyContent:'space-between'}}>
      <img src='./chanel.png' />
      <img src='./BURBERRY.png' />
      <img src='./ESPRIT.png'/>
      <img src='./Brand.png'/>

    </div>

     </div>
      
 
      <div className='container'>
      <div className='services'>
        <AboutCard header="" subheader="" image="./analytics.png"/>
        <AboutCard header="" subheader="" image="./gift.png"/>
        <AboutCard header="" subheader="" image="./graph.png"/>
        <AboutCard header="" subheader="" image="./call.png"/>
        <AboutCard header="" subheader="" image="./competition.png"/>
        <AboutCard header="" subheader="" image="./seo.png"/>
          </div>

      </div>
      <div className='partners'>
     <span  className='body__header'>Сейчас ты узнаешь своих конкурентов.{"\n"} Завтра ты их устранишь. 
</span>

    <form className='align' style={{gap:"15px", justifyContent:"center"}}>
      <input className='custom-input' placeholder='Введите URL, domain страницы для анализа'></input>
      <button className='custom-button'>Обработать</button>
    </form>

     </div>
  
    </>
  )
}
